public with sharing class OppTriggerHelper {
    public OppTriggerHelper() {

    }
    public void doTask1() {
        System.debug('Task 1');
    }
    public void doTask2() {
        System.debug('Task 2');
    }
    public void doTask3() {
        System.debug('Task 3');
    }
    public void doTask4() {
        System.debug('Task 4');
    }
    public void doTask5() {
        System.debug('Task 5');
    }

    
}